### ISSUE TITLE
publish on yarn registry

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/three-cad-viewer#4]
Currently my VSCode extension attempt uses static files I manually download from the release page in this repository, and I don't want to commit them.

In order to correctly deal with the three-cad-viewer dependency, it could be appreciated to publish the package in the Yarn registry, as you did with [jupyter_cadquery](https://yarnpkg.com/package/jupyter_cadquery), and update it for each release. 🙂

**Comment by bernhard-42** [comment]
I do have a preference for yarn for development. I just have an already active npm account from the past, that's why I still publish to npm ...

**Comment by roipoussiere** [comment]
Ok! Btw I naively searched for "cadquery". Maybe if you add this term as keyword (eventually among some others) in npm / github it will facilitate the package discovery?

**Comment by bernhard-42** [comment]
`three-cad-viewer` is completely independent of Juypter-CadQuery. You can use it with any tool the outputs tessellated 3D objects.

`cad-viewer-widget` uses `three-cad-viewer` and add an ipywidget layer on top of it. Just to be able to interact between Python and Javascript. Still, no CadQuery needed. In fact, one of the examples is built with pythonocc.

Finally, `Jupyter-Cadquery` transforms CadQuery objects into a format `three-cad-viewer` understands and uses `cad-viewer-widget` for communication between Python and Javascript.

That's why I didn't think of adding any cadquery tag ;-)
